config.yaml
lib/charms/nginx_ingress_integrator/v0/nginx_route.py
src/charm.py
templates/config.jinja
tests/unit/test_charm.py

Adds `web-proxy` as a config value and updates `config.jinja` to include this value when provided if google oauth credentials are also provided.

CSS-5072 add web-proxy as a config value

---

CONTRIBUTING.md
config.yaml
src/charm.py
templates/config.jinja
tests/integration/conftest.py
tests/integration/helpers.py
tests/unit/test_charm.py

Adds the worker function to the trino charm. 
Includes:
- Update to the `config.properties` to allow for different configuration if the `charm-function` is set to `worker` vs `coordinator` vs `all`. All to be used for single node testing.
- Opening of the service port 8080 such that the workers can announce their presence to the discovery_uri

CSS-5261 Add worker function

---

requirements.txt
tests/integration/helpers.py
tests/integration/test_charm.py
tests/integration/test_policy.py
tests/integration/trino_client/show_catalogs.py
tox.ini

Add integration tests for the policy relation. The test:
- Deploys Ranger and PostgreSQL charms
- Relates Trino and Ranger
- Creates policies in Ranger
- Verifies these policies are applied to users accessing Trino

CSS-5987 integration testing for policy relation

---

.licenserc.yaml
lib/charms/nginx_ingress_integrator/v0/nginx_route.py
metadata.yaml
src/charm.py
src/connector.py
src/literals.py
src/relations/policy.py
src/utils.py
templates/access-control.properties
templates/password-authenticator.jinja
templates/ranger-plugin.jinja
tests/integration/conftest.py
tests/integration/helpers.py
tests/integration/test_policy.py
tests/unit/test_charm.py
tox.ini

This PR updates the charm to use the trino rock. This required:
- Some updates to ranger and trino home pathways
- Removal of unpacking the tar from the charm as this is now handled by the rock
- Update to the entrypoint
- Update to environment variables to include the required paths for the install.properties
- Update to tests given the above.
- Removal of value restrictions for plugins not included in the ROCK
Due to changes in Ranger the following was updates:
Ranger no longer synchronizes via a file and relation to Trino. The way we handle this moving forward has not been determined so I have left in this option, however I have updated the integration test to validate policies which apply to the user not the group until we have a clear pathway forward.
Some general refactors:
- Adding …

CSS-7960 Trino rock and refactor

---

lib/charms/loki_k8s/v0/loki_push_api.py
lib/charms/prometheus_k8s/v0/prometheus_scrape.py
src/charm.py
tests/unit/test_charm.py

This is a fix for an error introduced when the catalog config contains the special character `{` as this causes `.format()` to error. Using `replace` instead ensures that the replacement is not broken by special characters. I've also added these characters in the password of the unit test.

Fix for when password contains `{` and lib update

---

config.yaml
src/charm.py
templates/config.jinja
tests/unit/test_charm.py

As our ldap synchronization will use email as the key we do not need any user mapping. While it's not needed for our use case it could still be useful for others who have a different source of users. Therefore instead of removing this value entirely this PR makes it an optional config.

CSS-8769 Make oauth user mapping an optional config

---

metadata.yaml

In the event that Ranger becomes unavailable, Trino will still be able to determine access controls based on its `policycache` - this PR mounts that as a volume so as to persist it. 
Please note: the upgrade in place does not work when the storage has been changed between upgrades. Therefore the safe-upgrade integration test is expected to fail, as this change is breaking. This test will still be relevant and expect to pass for future upgrades where no change has been made to the storage.

CSS-10040 adds storage for ranger policy cache

---

README.md
src/charm.py
tests/unit/helpers.py
tests/unit/test_charm.py

Update the secret structure to store all usernames and passwords under 1 key. This is due to juju secret keys not being allowed to include `_` this provides the flexibility to have the usernames contain this character.

update secret structure

---

config.yaml
src/charm.py
src/literals.py
src/utils.py
templates/jvm.jinja
tests/unit/helpers.py
tests/unit/test_charm.py

This PR makes the Trino JVM options configurable for the purpose of optimization. This should be a temporary update to give us more control over the jvm properties in order to optemise trino, with the long term plan of eventually providing configurable profiles (`production`, `staging`, `development`) with the jvm values pre-selected for these environments.
This introduces a number of addition configuration values:
- Individual values for those properties which have a high optimisation potential (meaning we may want to tweak frequently in testing). For these I believe we would always want to include the option the only change would be to the value - please let me know if you see a scenario for one of these where we would want to remove it entirely and I can adjust for this.
- …

CSS-10284 Make Trino jvm options configurable

---

src/charm.py
src/relations/trino_coordinator.py
src/relations/trino_worker.py

This PR:
- Passes the juju secret id from coordinator to worker so that users are consistent between the two applications without needing to set the config once for each. 
- Adds a blocked status if there is an error getting the secret content.
- Moves the update of the db to the `_update` method as this is then called on relation changed events between coordinator and worker,

Improve Trino Secret handing

---

.github/workflows/integration_test.yaml
.github/workflows/test_and_publish_charm.yaml
README.md
requirements.txt
src/charm.py
src/literals.py
src/utils.py
tests/integration/helpers.py
tests/unit/helpers.py
tests/unit/test_charm.py
tox.ini

With the existing structure of the catalog-config.yaml file, this quickly becomes large enough that k8s secrets no longer support the size resulting in an error when adding additional catalogs. https://warthogs.atlassian.net/browse/CSS-10465
This PR:
- Updates the config file format to use a backend structure to prevent repetition when adding multiple databases from the same server.
- Adds logic to the charm code for reading this config and turning it into catalogs in trino. 
Please note, for now this just supports the addition of `postgresql` connectors, in the future we can add additional backends and charm logic for other supported connectors but it is very hard to generalised for all as every connector differs considerably in configuration values.

CSS-10465 update trino secret format

---

metadata.yaml
src/charm.py
src/literals.py
src/relations/opensearch.py
src/relations/policy.py
src/utils.py
tests/unit/test_charm.py
tests/unit/test_policy.py

This PR basically removes references to Java in the charm, so that we can update the rock without updating the charm. However, we do expect the rock to configure JAVA_HOME
p.s: integration tests would fail until I update the rock. So the [PR](https://github.com/canonical/charmed-trino-rock/pull/11) on the rock should be merged before.

CSS-10565: java home is set in the rock

---

src/charm.py
src/utils.py
tests/unit/test_charm.py
tests/unit/test_policy.py

`"$JAVA_HOME/lib/security/cacerts"`, was being interpreted as the string `JAVA_HOME` and so failing to update the cacerts password. This PR gets the value from the environment and then uses it directly in the exec command.
It also removes the debug logging of the error when failing to update the catalog as this logs also the secret. I'll create another PR for better error handling but  this is to immediately remove this.

update java home to use environment variable not string

---

README.md
lib/charms/data_platform_libs/v0/data_interfaces.py
src/catalog_manager.py
src/charm.py
src/literals.py
src/utils.py
tests/integration/helpers.py
tests/integration/test_charm.py
tests/unit/helpers.py
tests/unit/test_charm.py
tests/unit/test_policy.py
tox.ini

This PR:
- Adds logic for handling bigquery connector. Mainly reading from a secret containing service account credentials and creating a `.properties` file with the appropriate values.
- Refactors the catalog-config and catalog handling methods in order to:
-- Move all credentials to juju secrets
-- Remove the expectation that only postgresql is used as the connector.
- Updates unit and integration tests to include bigquery and work with refactoring
- Updated `README` with instructions on creating juju secrets and applying the catalog.
Note: the private key included for testing is a self signed throw away for use with integration tests. (trino will error if attempts to decode it fail). Open to alternatives as to where this should be kept.

CSS-11010 Add bigquery connector and refactor catalog handling

---

config.yaml
src/charm.py
templates/config.jinja
tests/unit/test_charm.py

Adds the following configuration values which are useful to be able to alter in a deployment:
- coordinator connect timeout
- worker request timeout
- coordinator request timeout
- maximum concurrent queries

CSS-11336 add timeout and max-concurrent-queries values as configs

---

config.yaml
src/literals.py
tests/integration/test_resources.py
tests/unit/helpers.py

Add the following properties as defaults
```
"-XX:+ExitOnOutOfMemoryError",
"-XX:+HeapDumpOnOutOfMemoryError",
```
Based on the recommendation here: https://trino.io/docs/current/installation/deployment.html#jvm-config
Additionally some reformatting of other files in line with black formatting requirements.

Formatting and adding additional jvm options

---

README.md
src/catalog_manager.py
src/charm.py
src/literals.py
tests/integration/helpers.py
tests/integration/test_charm.py
tests/integration/test_resources.py
tests/unit/helpers.py
tests/unit/test_charm.py
tox.ini

This PR adds the logic for adding the service account credentials and catalog for the google sheet connector. 
Please note the service account credentials included here are purely for testing, they are self signed certificates I have generated locally and the account does not exist.
It also adds:
- Unit tests
- Integration tests
- Documentation on the connector
Note: pinning websockets version was required due to: https://github.com/juju/python-libjuju/issues/1184

CSS-11844 Adds the google sheet connector

---

README.md
requirements.txt
src/catalog_manager.py
src/charm.py
src/literals.py
tests/integration/helpers.py
tests/integration/test_charm.py
tests/unit/helpers.py
tests/unit/test_charm.py

Added support for mysql catalogs (the configuration is quite similar to postgresql, with the difference that they don't seem to specify a database name)

CSS-12576 add support for mysql catalogs

---

CONTRIBUTING.md
README.md
src/catalog_manager.py
src/charm.py
src/sql_catalog.py
tests/integration/helpers.py
tests/integration/test_charm.py
tests/unit/helpers.py
tests/unit/test_charm.py
trino_rock/rockcraft.yaml

This PR adds [Redshift Trino connector](https://trino.io/docs/current/connector/redshift.html) to trino-k8s-operator. 
* Moved SqlCatalog class to a new module without changing its code. I just extended this class for a slight change for Redshift by adding `_get_db_url` function.
* Changed the Rockfile for Trino to enable Redshift plugin.
* Fixed and extended Contributing.md document. It was stale so I needed to update it. I also added some new details for handling rocks.

Added Redshift Trino connector

---

lib/charms/data_platform_libs/v0/data_interfaces.py
src/charm.py
src/relations/trino_coordinator.py

Current implementation of `_on_config_changed` ends up calling `_update` twice. It causes a race condition between catalog files being created twice and `trino` reading them. This PR attempts to fix it.
Note that there has not been enough manual testing for the changes.

fix: do not call update twice per config change

---

.github/workflows/integration_test.yaml
requirements-dev.txt
src/charm.py

As outlined in [CSS-17394](https://warthogs.atlassian.net/browse/CSS-17394), we've been getting a number of instances where Trino responds with `502 bad gateway`. A potential cause of this is:
- The charm has been using `http://localhost:8080/` as it's health check endpoint. In the Helm charts, it uses `http://localhost:8080/v1/info` as this returns a JSON rather than generating HTML as the first endpoint does.
- In the `update_status` hook, once the up check fails, the charm calls `self._restart_trino()`, causing Trino to constantly restart. This results in the following output of `juju show-status-log trino-coordinator/0`:
```
Time                   Type       Status       Message
16 Sep 2025 16:02:03Z  juju-unit  executing    running trino-pebble-check-failed hook
16 Sep 2025 16:02:08Z …
```

[CSS-17394] - Update health check endpoint and tox deps
